# Full Clone Example
# This file demonstrates cloning an XSOAR configuration using Terraform.
# Generated by the xsoar-export tool, then modified for the target instance.

# Server configuration
resource "cortex_server_config" "session_timeout" {
  key   = "session.timeout"
  value = "60"
}

resource "cortex_server_config" "concurrent_jobs" {
  key   = "content.jobs.concurrent"
  value = "10"
}

# Password policy
resource "cortex_password_policy" "main" {
  min_length                 = 12
  min_length_enabled         = true
  min_lowercase              = 1
  min_lowercase_enabled      = true
  min_uppercase              = 1
  min_uppercase_enabled      = true
  min_digits                 = 1
  min_digits_enabled         = true
  min_special                = 1
  min_special_enabled        = true
  max_failed_attempts        = 5
  max_failed_attempts_enabled = true
  expiration_days            = 90
  expiration_days_enabled    = true
}

# Jobs
resource "cortex_job" "daily_cleanup" {
  name         = "Daily Incident Cleanup"
  playbook_id  = "CloseStaleIncidents"
  scheduled    = true
  cron         = "0 2 * * *"
  recurrent    = true
}

# Pre-processing rules
resource "cortex_preprocessing_rule" "dedup" {
  name        = "Deduplicate Incidents"
  enabled     = true
  action      = "drop"
  rules_json  = jsonencode({
    "FILTER" = {
      "filter" = {
        "AND" = [
          {
            "SEARCH_FIELD" = "name"
            "SEARCH_TYPE"  = "EQ"
            "SEARCH_VALUE" = ""
          }
        ]
      }
    }
  })
}

# Backup config
resource "cortex_backup_config" "main" {
  enabled        = true
  schedule_cron  = "0 3 * * *"
  retention_days = 30
  path           = "/var/lib/demisto/backup"
}
