# Full Clone Example
# This file demonstrates cloning an XSOAR configuration using Terraform.
# Generated by the xsoar-export tool, then modified for the target instance.

# Server configuration (XSOAR 6 / XSOAR 8 SaaS only, not XSIAM)
resource "cortex_server_config" "session_timeout" {
  key   = "session.timeout"
  value = "60"
}

resource "cortex_server_config" "concurrent_jobs" {
  key   = "content.jobs.concurrent"
  value = "10"
}

# Password policy
resource "cortex_password_policy" "main" {
  min_length                  = 12
  min_length_enabled          = true
  min_lowercase               = 1
  min_lowercase_enabled       = true
  min_uppercase               = 1
  min_uppercase_enabled       = true
  min_digits                  = 1
  min_digits_enabled          = true
  min_special                 = 1
  min_special_enabled         = true
  max_failed_attempts         = 5
  max_failed_attempts_enabled = true
  expiration_days             = 90
  expiration_days_enabled     = true
}

# Jobs (cron-based for XSOAR 6/8)
resource "cortex_job" "daily_cleanup" {
  name               = "Daily Incident Cleanup"
  playbook_id        = "CloseStaleIncidents"
  type               = "Housekeeping"
  scheduled          = true
  cron               = "0 2 * * *"
  recurrent          = true
  should_trigger_new = true
  tags               = ["maintenance"]
}

# Pre-processing rules
resource "cortex_preprocessing_rule" "dedup" {
  name       = "Deduplicate Incidents"
  enabled    = true
  action     = "drop"
  rules_json = jsonencode({
    "FILTER" = {
      "filter" = {
        "AND" = [
          {
            "SEARCH_FIELD" = "name"
            "SEARCH_TYPE"  = "EQ"
            "SEARCH_VALUE" = ""
          }
        ]
      }
    }
  })
}

# Backup config (V6 only)
resource "cortex_backup_config" "main" {
  enabled        = true
  schedule_cron  = "0 3 * * *"
  retention_days = 30
  path           = "/var/lib/demisto/backup"
}

# Credentials
resource "cortex_credential" "svc_ticketing" {
  name     = "svc-ticketing"
  user     = "ticketing_api"
  password = var.ticketing_password
  comment  = "Ticketing system API account"
}

# Exclusion list
resource "cortex_exclusion_list" "internal" {
  value  = "10.0.0.0/8"
  type   = "CIDR"
  reason = "Internal network"
}

# Lists
resource "cortex_list" "allowed_senders" {
  name = "AllowedEmailSenders"
  type = "plain_text"
  data = "noreply@example.com\nalerts@monitoring.example.com"
}

resource "cortex_list" "config" {
  name = "AutomationConfig"
  type = "json"
  data = jsonencode({
    max_retries = 3
    timeout     = 30
  })
}

# Marketplace packs
resource "cortex_marketplace_pack" "common_scripts" {
  pack_id = "CommonScripts"
  version = "1.13.38"
}

# Variables
variable "ticketing_password" {
  description = "Ticketing system password"
  type        = string
  sensitive   = true
}
